import axios from 'axios'

export const CLIENT_GATEWAY_URL = process.env.REACT_APP_GATEWAY_URL
export const clientGateway = axios.create({
  baseURL: CLIENT_GATEWAY_URL
})

export enum ModalTypes {
  ADD_PARTICIPANT,
  DELETE_MESSAGE,
  INCOMING_CALL,
  NEW_COMMUNITY,
  NEW_CONVERSATION,
  PREVIEW_IMAGE,
  STATUS
}

export enum Events {
  NEW_MESSAGE = 'NEW_MESSAGE',
  DELETED_MESSAGE = 'DELETED_MESSAGE',
  NEW_PARTICIPANT = 'NEW_PARTICIPANT',
  DELETED_PARTICIPANT = 'DELETED_PARTICIPANT',
  NEW_MEMBER = 'NEW_MEMBER',
  DELETED_MEMBER = 'DELETED_MEMBER',
  NEW_CHANNEL = 'NEW_CHANNEL',
  DELETED_CHANNEL = 'DELETED_CHANNEL',
  TYPING = 'TYPING',
  NEW_VOICE_SESSION = 'NEW_VOICE_SESSION',
  ACCEPTED_VOICE_SESSION = 'ACCEPTED_VOICE_SESSION',
  NEW_MENTION = 'NEW_MENTION',
  UPDATED_CONVERSATION = 'UPDATED_CONVERSATION',
  UPDATED_MESSAGE = 'UPDATED_MESSAGE'
}

export enum MessageTypes {
  NORMAL = 1,
  PINNED = 2,
  MEMBER_ADDED = 3,
  MEMBER_REMOVED = 4,
  ADMINISTRATOR = 5
}

export enum ChannelTypes {
  PrivateChannel,
  GroupChannel,
  CommunityChannel
}
