import axios from 'axios'

export const CLIENT_GATEWAY_URL = process.env.REACT_APP_GATEWAY_URL
export const clientGateway = axios.create({
  baseURL: CLIENT_GATEWAY_URL
})

export enum ModalTypes {
  ADD_PARTICIPANT,
  DELETE_MESSAGE,
  INCOMING_CALL,
  NEW_COMMUNITY,
  NEW_CONVERSATION,
  NEW_PERMISSION,
  PREVIEW_IMAGE,
  STATUS
}

export enum Permissions {
  READ_MESSAGES = 1,
  SEND_MESSAGES = 2,
  EMBED_LINKS = 3,
  MENTION_MEMBERS = 4,
  MENTION_ROLES = 5,
  MENTION_EVERYONE = 6,
  MENTION_SOMEONE = 7,
  CREATE_INVITES = 8,
  BAN_MEMBERS = 9,
  KICK_MEMBERS = 10,
  MANAGE_PERMISSIONS = 11,
  MANAGE_CHANNELS = 12,
  MANAGE_INVITES = 13,
  MANAGE_SERVER = 14,
  MANAGE_MESSAGES = 15,
  ADMINISTRATOR = 16,
  OWNER = 17
}

export enum Events {
  NEW_MESSAGE = 'NEW_MESSAGE',
  DELETED_MESSAGE = 'DELETED_MESSAGE',
  NEW_PARTICIPANT = 'NEW_PARTICIPANT',
  DELETED_PARTICIPANT = 'DELETED_PARTICIPANT',
  NEW_MEMBER = 'NEW_MEMBER',
  DELETED_MEMBER = 'DELETED_MEMBER',
  NEW_CHANNEL = 'NEW_CHANNEL',
  DELETED_CHANNEL = 'DELETED_CHANNEL',
  TYPING = 'TYPING',
  NEW_VOICE_SESSION = 'NEW_VOICE_SESSION',
  ACCPETED_VOICE_SESSION = 'ACCPETED_VOICE_SESSION',
  NEW_MENTION = 'NEW_MENTION',
  UPDATED_CONVERSATION = 'UPDATED_CONVERSATION'
}

export enum ChannelTypes {
  PrivateChannel,
  GroupChannel,
  CommunityChannel
}
